### ISSUE TITLE
FFmpeg exited with code: 1 and signal: null (Error)

### ISSUE THREAD

**Issue by litex2x** [potmat/homebridge-google-nest-sdm#204]
**Have you read the [FAQ](https://github.com/potmat/homebridge-google-nest-sdm#faq)?**

Yes

**Have you searched [existing issues](https://github.com/potmat/homebridge-google-nest-sdm/issues?q=is%3Aissue)?**

Yes

**Have you searched [existing discussions](https://github.com/potmat/homebridge-google-nest-sdm/discussions?discussions_q=)?**

Yes

**Describe the bug**
I have a Google Doorbell Wired (Gen 2). I have been running this plugin for a quite a while without issue. I just noticed yesterday the stream was not working. Seems like the stream file is not being created and it is not clear to me why.  See debug log below.

**Attach Logs**
```
[10/10/2025, 5:45:41 PM] [homebridge-google-nest-sdm] Video stream requested: 1280 x 720, 30 fps, 299 kbps Living Room Doorbell
[10/10/2025, 5:45:41 PM] [homebridge-google-nest-sdm] Executing command sdm.devices.commands.CameraLiveStream.GenerateWebRtcStream with parameters {"offerSdp":"v=0\r\no=- 10374993 0 IN IP4 0.0.0.0\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1 2\r\na=extmap-allow-mixed\r\na=msid-semantic:WMS *\r\nm=audio 9 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:872d\r\na=ice-pwd:aaaf29131e8385323faab5\r\na=ice-options:trickle\r\na=fingerprint:sha-256 83:11:42:1F:45:DA:65:2D:85:26:4E:74:E6:40:2C:D2:F1:C8:B9:D3:66:EE:8D:F8:75:29:99:26:22:03:14:45\r\na=setup:actpass\r\na=recvonly\r\na=mid:0\r\na=msid:3b02a9d3-4c9d-4347-aa59-d1d71c05c764 fa3ff5bb-6965-49d8-892d-2b81e8214422\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtcp-mux\r\na=ssrc:2932606423 cname:2b25feeb-1a44-447c-8ca5-ff08a8b6d8d2\r\na=rtpmap:96 opus/48000/2\r\nm=video 9 UDP/TLS/RTP/SAVPF 97\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:872d\r\na=ice-pwd:aaaf29131e8385323faab5\r\na=ice-options:trickle\r\na=fingerprint:sha-256 83:11:42:1F:45:DA:65:2D:85:26:4E:74:E6:40:2C:D2:F1:C8:B9:D3:66:EE:8D:F8:75:29:99:26:22:03:14:45\r\na=setup:actpass\r\na=recvonly\r\na=mid:1\r\na=msid:75af5fea-a00d-4aa5-a7b2-185c87c83d2b d1e6920f-b7ae-4f57-8e6f-fe3decb0c686\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=rtcp-mux\r\na=ssrc:1410030334 cname:2b25feeb-1a44-447c-8ca5-ff08a8b6d8d2\r\na=rtpmap:97 H264/90000\r\na=rtcp-fb:97 transport-cc\r\na=rtcp-fb:97 ccm fir\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=rtcp-fb:97 goog-remb\r\na=fmtp:97 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\nm=application 9 UDP/DTLS/SCTP webrtc-datachannel\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:872d\r\na=ice-pwd:aaaf29131e8385323faab5\r\na=ice-options:trickle\r\na=fingerprint:sha-256 83:11:42:1F:45:DA:65:2D:85:26:4E:74:E6:40:2C:D2:F1:C8:B9:D3:66:EE:8D:F8:75:29:99:26:22:03:14:45\r\na=setup:actpass\r\na=mid:2\r\na=sctp-port:5000\r\na=max-message-size:65536\r\n"} Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm] Execution of command sdm.devices.commands.CameraLiveStream.GenerateWebRtcStream returned {"answerSdp":"v=0\r\no=- 0 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 2 1\r\na=msid-semantic: WMS 18315760383554192392/1446261547 virtual-6666\r\na=ice-lite\r\nm=audio 19305 UDP/TLS/RTP/SAVPF 96\r\nc=IN IP4 74.125.247.225\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=candidate: 1 udp 2113939711 2001:4860:4864:4:4000::11 19305 typ host generation 0\r\na=candidate: 1 tcp 2113939710 2001:4860:4864:4:8000::10 19305 typ host tcptype passive generation 0\r\na=candidate: 1 ssltcp 2113939709 2001:4860:4864:4:8000::10 443 typ host generation 0\r\na=candidate: 1 udp 2113932031 74.125.247.225 19305 typ host generation 0\r\na=candidate: 1 tcp 2113932030 74.125.247.134 19305 typ host tcptype passive generation 0\r\na=candidate: 1 ssltcp 2113932029 74.125.247.134 443 typ host generation 0\r\na=ice-ufrag:U9tB-BleGCguAgoKAAiSWigaIAEQ\r\na=ice-pwd:nsTFebO3VaPMVpdMxLt62k33QCs=\r\na=fingerprint:sha-256 A4:48:31:0D:B3:CC:2B:09:66:3F:F4:3E:BA:B5:7D:FE:60:EA:BB:B0:C1:C0:6A:0E:3E:72:E4:98:7F:55:1D:E2\r\na=setup:passive\r\na=mid:0\r\na=sendrecv\r\na=msid:virtual-6666 virtual-6666\r\na=rtcp-mux\r\na=rtpmap:96 opus/48000/2\r\na=fmtp:96 minptime=10;useinbandfec=1\r\na=ssrc:6666 cname:6666\r\nm=video 9 UDP/TLS/RTP/SAVPF 97\r\nc=IN IP4 0.0.0.0\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=ice-ufrag:U9tB-BleGCguAgoKAAiSWigaIAEQ\r\na=ice-pwd:nsTFebO3VaPMVpdMxLt62k33QCs=\r\na=fingerprint:sha-256 A4:48:31:0D:B3:CC:2B:09:66:3F:F4:3E:BA:B5:7D:FE:60:EA:BB:B0:C1:C0:6A:0E:3E:72:E4:98:7F:55:1D:E2\r\na=setup:passive\r\na=mid:1\r\na=sendrecv\r\na=msid:18315760383554192392/1446261547 18315760383554192392/1446261547\r\na=rtcp-mux\r\na=rtpmap:97 H264/90000\r\na=rtcp-fb:97 ccm fir\r\na=rtcp-fb:97 nack\r\na=rtcp-fb:97 nack pli\r\na=rtcp-fb:97 goog-remb\r\na=fmtp:97 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f\r\na=ssrc:1446261547 cname:1446261547\r\nm=application 9 DTLS/SCTP 5000\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:U9tB-BleGCguAgoKAAiSWigaIAEQ\r\na=ice-pwd:nsTFebO3VaPMVpdMxLt62k33QCs=\r\na=fingerprint:sha-256 A4:48:31:0D:B3:CC:2B:09:66:3F:F4:3E:BA:B5:7D:FE:60:EA:BB:B0:C1:C0:6A:0E:3E:72:E4:98:7F:55:1D:E2\r\na=setup:passive\r\na=mid:2\r\na=sctpmap:5000 webrtc-datachannel 1024\r\n","expiresAt":"2025-10-11T00:50:42.835192Z","mediaSessionId":"U9tB-BleGCguAgoKAAiSWigaIAEQ"} Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm] Stream command: /homebridge/node_modules/homebridge-google-nest-sdm/node_modules/ffmpeg-for-homebridge/ffmpeg -protocol_whitelist pipe,crypto,udp,rtp,fd -analyzeduration 15000000 -probesize 100000000 -i - -an -sn -dn -codec:v copy -f rawvideo -pix_fmt yuv420p -color_range mpeg -payload_type 99 -ssrc 13785491 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params EFaDTo/1kIfu+xdZdCMtRcTBcvBFLMNpgbAYMrLY srtp://192.168.1.41:59909?rtcpport=59909&pkt_size=1378 -vn -sn -dn -codec:a libfdk_aac -profile:a aac_eld -flags +global_header -ar 16k -b:a 24k -ac 1 -payload_type 110 -ssrc 10417345 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params ll2jknujyvXqSREyiUP4Sh+TeXlprJLt9nCjv48O srtp://192.168.1.41:52430?rtcpport=52430&pkt_size=188 -loglevel level+verbose v=0
o=- 0 0 IN IP4 127.0.0.1
s=-
c=IN IP4 127.0.0.1
t=0 0
m=audio 13025 UDP 96
a=rtpmap:96 opus/48000/2
a=fmtp:96 minptime=10;useinbandfec=1
a=rtcp-fb:96 transport-cc
a=sendrecv
m=video 10190 UDP 97
a=rtpmap:97 H264/90000
a=rtcp-fb:97 ccm fir
a=rtcp-fb:97 nack
a=rtcp-fb:97 nack pli
a=rtcp-fb:97 goog-remb
a=fmtp:97 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=sendrecv Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm] [info] ffmpeg version 6.0-homebridge-alpine-x86_64-static Copyright (c) 2000-2023 the FFmpeg developers Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm] [info]   built with gcc 12.2.1 (Alpine 12.2.1_git20220924-r10) 20220924 Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm]  Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm] [info]   configuration: --enable-hardcoded-tables --enable-nonfree --enable-gpl --enable-hardcoded-tables --enable-hardcoded-tables --enable-openssl --enable-libdav1d --enable-libsvtav1 --enable-libx264 --enable-libx265 --enable-libvpx --enable-libxvid --enable-libvidstab --enable-libaom --enable-libzimg --enable-lv2 --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libtheora --enable-libfdk-aac --enable-libwebp --enable-libsrt --enable-libvpl --enable-vaapi --disable-ffnvcodec --enable-amf --disable-debug --disable-shared --enable-pthreads --enable-static --enable-version3 --extra-cflags='-I/build/workspace/include -I/build/workspace/include/lilv-0' --extra-ldexeflags=-static --extra-ldflags=-L/build/workspace/lib --extra-libs='-ldl -lpthread -lm -lz' --pkgconfigdir=/build/workspace/lib/pkgconfig --pkg-config-flags=--static --prefix=/build/workspace --extra-version=homebridge-alpine-x86_64-static Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm] [info]   libavutil      58.  2.100 / 58.  2.100 Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm] [info]   libavcodec     60.  3.100 / 60.  3.100 Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm] [info]   libavformat    60.  3.100 / 60.  3.100 Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm] [info]   libavdevice    60.  1.100 / 60.  1.100 Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm] [info]   libavfilter     9.  3.100 /  9.  3.100 Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm] [info]   libswscale      7.  1.100 /  7.  1.100 Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm] [info]   libswresample   4. 10.100 /  4. 10.100 Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm] [info]   libpostproc    57.  1.100 / 57.  1.100 Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm]  Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm] [sdp @ 0x7f0c268b2840] [verbose] setting jitter buffer size to 500 Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm]  Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm] [sdp @ 0x7f0c268b2840] [verbose] setting jitter buffer size to 500 Living Room Doorbell
[10/10/2025, 5:45:42 PM] [homebridge-google-nest-sdm]  Living Room Doorbell
[10/10/2025, 5:45:52 PM] [homebridge-google-nest-sdm] [sdp @ 0x7f0c268b2840] [warning] Could not find codec parameters for stream 1 (Video: h264, 1 reference frame, none): unspecified size Living Room Doorbell
[10/10/2025, 5:45:52 PM] [homebridge-google-nest-sdm] Consider increasing the value for the 'analyzeduration' (15000000) and 'probesize' (100000000) options Living Room Doorbell
[10/10/2025, 5:45:52 PM] [homebridge-google-nest-sdm]  Living Room Doorbell
[10/10/2025, 5:45:52 PM] [homebridge-google-nest-sdm] [info] Input #0, sdp, from 'fd:': Living Room Doorbell
[10/10/2025, 5:45:52 PM] [homebridge-google-nest-sdm] [info]   Metadata: Living Room Doorbell
[10/10/2025, 5:45:52 PM] [homebridge-google-nest-sdm] [info]     title           : - Living Room Doorbell
[10/10/2025, 5:45:52 PM] [homebridge-google-nest-sdm] [info]   Duration: N/A, bitrate:  Living Room Doorbell
[10/10/2025, 5:45:52 PM] [homebridge-google-nest-sdm] N/A Living Room Doorbell
[10/10/2025, 5:45:52 PM] [homebridge-google-nest-sdm] [info]   Stream #0:0: Audio: opus, 48000 Hz, stereo, fltp Living Room Doorbell
[10/10/2025, 5:45:52 PM] [homebridge-google-nest-sdm] [info]   Stream #0:1: Video: h264, 1 reference frame, none, 45k tbr, 90k tbn Living Room Doorbell
[10/10/2025, 5:45:52 PM] [homebridge-google-nest-sdm] [info] Output #0, rtp, to 'srtp://192.168.1.41:59909?rtcpport=59909&pkt_size=1378': Living Room Doorbell
[10/10/2025, 5:45:52 PM] [homebridge-google-nest-sdm] [out#0/rtp @ 0x7f0c2680b580] [error] Output file does not contain any stream Living Room Doorbell
[10/10/2025, 5:45:52 PM] [homebridge-google-nest-sdm]  Living Room Doorbell
[10/10/2025, 5:45:52 PM] [homebridge-google-nest-sdm] [AVIOContext @ 0x7f0c268b1840] [verbose] Statistics: 397 bytes read, 0 seeks Living Room Doorbell
[10/10/2025, 5:45:52 PM] [homebridge-google-nest-sdm]  Living Room Doorbell
[10/10/2025, 5:45:52 PM] [homebridge-google-nest-sdm] FFmpeg exited with code: 1 and signal: null (Error) Living Room Doorbell
[10/10/2025, 5:45:52 PM] [homebridge-google-nest-sdm] Executing command sdm.devices.commands.CameraLiveStream.StopWebRtcStream with parameters {"mediaSessionId":"U9tB-BleGCguAgoKAAiSWigaIAEQ"} Living Room Doorbell
[10/10/2025, 5:45:54 PM] [homebridge-google-nest-sdm] Execution of command sdm.devices.commands.CameraLiveStream.StopWebRtcStream returned undefined Living Room Doorbell
[10/10/2025, 5:45:54 PM] [homebridge-google-nest-sdm] Stopped video stream. Living Room Doorbell
```

**Screenshots**
N/A

**Environment**
Homebridge v1.11.0
Plugin v1.1.23 

**Additional context**
Audio stream is enabled.

**Comment by litex2x** [comment]
This seems to be a WebRTC problem and not a plugin issue. There is no data coming through the stream after establishing connection. I created an issue [here](https://issuetracker.google.com/issues/451389799). It might be a while before it is fixed.

**Comment by ajean1899** [comment]
Running into the same issue as well Homebridge version 1.11.0, plugin version 1.1.23. Tried adding custom FFMPEG options, using the non native FFMPEG and still not working for me on any of my cameras

**Comment by litex2x** [comment]
> Running into the same issue as well Homebridge version 1.11.0, plugin version 1.1.23. Tried adding custom FFMPEG options, using the non native FFMPEG and still not working for me on any of my cameras

Google must've changed something with how they handle dtls that impacted werift. The video and audio transceiver subscribers are not receiving any data anymore.  I am able to pull up my stream in https://device-access-sample.web.app/ so it doesn't appear to be an outage of any kind. I created a werift [issue](https://github.com/shinyoshiaki/werift-webrtc/issues/513) because that is probably where a change is needed.

**Comment by lechlerjr** [comment]
I wanted to add that I too am running into the same issue. I even rebuilt homebridge from scratch and same problem.

One thing worth mentioning is that Google seems to have made a change that only affects Google Nest cams (white ones) or cameras that are Google branded. This plug-in still works for the legacy Nest camera (all black one) I have.

**Comment by litex2x** [comment]
> I wanted to add that I too am running into the same issue. I even rebuilt homebridge from scratch and same problem.
> 
> One thing worth mentioning is that Google seems to have made a change that only affects Google Nest cams (white ones) or cameras that are Google branded. This plug-in still works for the legacy Nest camera (all black one) I have.

Yeah this seems to impact webrtc streams the newer cams use. We are going to have to wait for webrift to fix the dtls issue.

**Comment by litex2x** [comment]
Google appears to have fixed whatever the issue was in their side
